CREATE TABLE "Categories" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY,
  "name" varchar,
  "id_parent" int,
  "view_name" varchar
);

CREATE TABLE "Entities" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY,
  "name" varchar,
  "category_id" int,
  "location" int
);

CREATE TABLE "Users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY,
  "name" varchar,
  "passwd" varchar,
  "email" varchar,
  "admin" bool
);

ALTER TABLE "Categories" ADD FOREIGN KEY ("id_parent") REFERENCES "Categories" ("id");

ALTER TABLE "Entities" ADD FOREIGN KEY ("category_id") REFERENCES "Categories" ("id");

ALTER TABLE "Entities" ADD FOREIGN KEY ("location") REFERENCES "Entities" ("id");
